name: Docker image scheduled build - No cache

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '23 1 * * *'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


permissions:
  contents: read

jobs:
  build-nocache:
    uses: Harvester57/reusable-workflows/.github/workflows/docker-reusable-scheduled-build.yml@main